spring:
  servlet:
    multipart:
      max-file-size: 118MB
      max-request-size: 118MB
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
    password:
  jpa:
    open-in-view: false
    database: postgresql
    database_platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
  liquibase:
    enabled: false
server:
  port: 8080

---

spring:
  profiles:
    active: develop
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: postgresql
    database_platform: org.hibernate.dialect.PostgreSQLDialect

---
mytones:
  auth.url: ${AUTH_SERVER_URL}